### ISSUE TITLE
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

### ISSUE THREAD

**Issue by brendon** [janko/image_processing#135]
Not sure what the oldest ImageMagick version is that you support, so it might require some kind of version detection to use the right command?

**Comment by janko** [comment]
Yeah, I support both IM 6 and 7. Did you update to latest MiniMagick 4.x? That one should fix the warning. I still have to merge in the MiniMagick 5.x compatibility.

**Comment by brendon** [comment]
Ah interesting. I just ran `bundle` so that might have been the issue. `bundle update` did the trick.

Still getting `Errno::EMFILE: Too many open files - magick` for the odd test :)

**Comment by janko** [comment]
Hmm, this doesn't indicate too many tempfiles, but the `magick` subprocess is hitting the limits. I just checked with `ulimit` that the file descriptor limit on my macOS is set to `unlimited`, so that's why I'm not seeing the issue. I could lower it to `1024` (common default) to try and reproduce it, but I don't have the bandwidth to then troubleshoot the root cause.

**Comment by brendon** [comment]
That's all good. I wonder if each time an image is processed in the tests it's not being closed properly? Might also explain the weird test failures in CI. This one doesn't bother me, so if it doesn't bother you then I guess it's all good to leave as is. It obviously only affects the tests or you'd have other people raising issues :)
